use hr;
--Select * from employees;
--QUESTION NO. 1
--SELECT first_name+' '+last_name as Full_Name, salary FROM employees WHERE salary < 6000;
--QUESTION NO. 2
--SELECT first_name,last_name,department_id,salary FROM employees WHERE salary > 8000;
--QUESTION NO. 3
--SELECT first_name,last_name,department_id FROM employees WHERE last_name = 'McEwen';
--QUESTION NO. 4
--SELECT * FROM employees	WHERE department_id IS NULL;
--QUESTION NO. 5
--SELECT first_name+' '+last_name AS Full_Name,hire_date,salary,department_id FROM employees WHERE first_name NOT LIKE '%m%' ;
--QUESTION NO. 6
--SELECT first_name+' '+last_name AS Full_Name, salary FROM employees WHERE commission_pct IS NULL;
--QUESTION NO. 7
--SELECT first_name+' '+last_name AS Full_Name, salary,email,phone_number FROM employees WHERE salary BETWEEN 9000 AND 17000;
--QUESTION NO. 8
--SELECT first_name,last_name, salary FROM employees WHERE first_name LIKE '%m';
--QUESTION NO. 9
--SELECT first_name+' '+last_name AS Full_Name, salary FROM employees WHERE salary NOT BETWEEN 7000 AND 15000;
--QUESTION NO. 10
--SELECT first_name+' '+last_name AS Full_Name, job_id,hire_date FROM employees WHERE hire_date BETWEEN '2007-11-05' AND '2009-07-05';
--QUESTION NO. 11
--SELECT first_name+' '+last_name AS Full_Name, department_id FROM employees WHERE department_id = 70 OR department_id = 90;
--QUESTION NO. 12
--SELECT first_name+' '+last_name AS Full_Name, salary, manager_id FROM employees WHERE manager_id IS NOT NULL;
--QUESTION NO. 13
--SELECT * FROM employees WHERE hire_date < '2002-06-21';
--QUESTION NO. 14
--SELECT first_name, last_name, email, salary, manager_id FROM employees WHERE manager_id = 120 OR manager_id = 103 OR manager_id = 145;
--QUESTION NO. 15
--SELECT * FROM employees WHERE first_name LIKE '%[D,S,N]%' ;
--QUESTION NO. 16
--SELECT first_name+' '+last_name AS 'Full_Name',hire_date, commission_pct,email+'_'+phone_number AS 'Contact_Details',salary FROM employees WHERE salary > 11000 OR phone_number LIKE '______3' ORDER BY first_name DESC;
--QUESTION NO. 17
--SELECT first_name,last_name,department_id FROM employees WHERE first_name LIKE '__s%' ;
--QUESTION NO. 18
--SELECT employee_id,first_name,job_id,department_id FROM employees WHERE department_id !=30 AND department_id !=50 AND department_id != 80;
--QUESTION NO. 19
--SELECT employee_id,first_name,job_id,department_id FROM employees WHERE department_id =30 OR department_id =40 OR department_id = 90;
--QUESTION NO. 20
--SELECT employee_id FROM employees WHERE employee_id IN (SELECT employee_id FROM job_history GROUP BY employee_id HAVING COUNT(employee_id) > 2);